import { readFile,writeFile } from "node:fs/promises"; import path from "node:path"; import { isLocalAdminRequest } from "@/lib/admin-access"; import type { ContentCollection,ContentStore } from "@/lib/content-types";
export const runtime="nodejs"; export const dynamic="force-dynamic"; const collections:ContentCollection[]=["certifications","projects","blog-posts","blog-categories"];
const denied=()=>Response.json({error:"Not found"},{status:404}); const valid=(v:unknown):v is ContentCollection=>typeof v==="string"&&collections.includes(v as ContentCollection); const file=(c:ContentCollection)=>path.join(process.cwd(),"content",`${c}.json`); const read=async(c:ContentCollection)=>JSON.parse(await readFile(file(c),"utf8")) as any[]; const save=async(c:ContentCollection,x:any[])=>writeFile(file(c),`${JSON.stringify(x,null,2)}\n`,`utf8`); const key=(c:ContentCollection,x:any)=>c==="blog-categories"?x.fr||x:x?.[c==="certifications"?"id":"slug"];
const localized=(x:any)=>typeof x==="object"&&x&&typeof x.fr==="string"?x:{fr:String(x??""),en:String(x??"")};
function validate(c:ContentCollection,item:any){if(c==="blog-categories")return localized(item).fr.trim()?null:"La catégorie française est obligatoire.";if(!item||typeof item!=="object")return "Contenu invalide.";const required=c==="certifications"?["id","title","subtitle","logo","kind","points"]:c==="projects"?["slug","title","shortDescription","year","category","image","problem","solution","audience","resolution","stack"]:["slug","title","shortDescription","coverImage","category","date","readTime","sections"];for(const field of required){const v=field in item?item[field]:undefined;if(v===undefined||v===null||(typeof v==="string"&&!v.trim())||(typeof v==="object"&&!localized(v).fr.trim()))return `Le champ « ${field} » est obligatoire.`}if(c==="certifications"&&(!Array.isArray(item.points)||item.points.length!==4||item.points.some((p:any)=>!localized(p).fr.trim())))return "Une certification doit contenir exactement quatre points.";if(c==="blog-posts"&&(!Array.isArray(item.sections)||!item.sections.length))return "Un article doit contenir au moins une section.";return null}
export async function GET(request:Request){if(!isLocalAdminRequest(request.headers))return denied();const entries=await Promise.all(collections.map(async c=>[c,await read(c)] as const));return Response.json(Object.fromEntries(entries) as ContentStore)}
export async function POST(request:Request){if(!isLocalAdminRequest(request.headers))return denied();const body=await request.json() as any;if(!valid(body.collection))return Response.json({error:"Collection invalide."},{status:400});const item=body.collection==="blog-categories"?localized(body.item):body.item;const error=validate(body.collection,item);if(error)return Response.json({error},{status:400});const items=await read(body.collection);if(items.some(x=>key(body.collection,x)===key(body.collection,item)))return Response.json({error:"Cet identifiant existe déjà."},{status:409});items.push(item);await save(body.collection,items);return Response.json({ok:true,item},{status:201})}
export async function PUT(request:Request){if(!isLocalAdminRequest(request.headers))return denied();const body=await request.json() as any;if(!valid(body.collection))return Response.json({error:"Collection invalide."},{status:400});const item=body.collection==="blog-categories"?localized(body.item):body.item;const error=validate(body.collection,item);if(error)return Response.json({error},{status:400});const items=await read(body.collection),index=items.findIndex(x=>key(body.collection,x)===body.key);if(index<0)return Response.json({error:"Contenu introuvable."},{status:404});items[index]=item;await save(body.collection,items);return Response.json({ok:true,item})}
export async function DELETE(request:Request){if(!isLocalAdminRequest(request.headers))return denied();const body=await request.json() as any;if(!valid(body.collection))return Response.json({error:"Collection invalide."},{status:400});const items=await read(body.collection),next=items.filter(x=>key(body.collection,x)!==body.key);if(next.length===items.length)return Response.json({error:"Contenu introuvable."},{status:404});await save(body.collection,next);return Response.json({ok:true})}
